version: '3'

services:
  
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ..:/workspace
    command: python /workspace/manage.py runserver 0.0.0.0:8000 --settings=opendiplomasproject.settings.development
    links:
      - 'db'

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data: